### ISSUE TITLE
amd64.rb:32:in `to_s': wrong number of arguments (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by expend20** [david942j/one_gadget#38]
[file](https://pwnable.tw/static/chall/secret_of_my_heart)

```
/var/lib/gems/2.3.0/gems/one_gadget-1.6.0/lib/one_gadget/fetchers/amd64.rb:32:in `to_s': wrong number of arguments (given 1, expected 0) (ArgumentError)
    from /var/lib/gems/2.3.0/gems/one_gadget-1.6.0/lib/one_gadget/fetchers/amd64.rb:32:in `jmp_case_candidates'
    from /var/lib/gems/2.3.0/gems/one_gadget-1.6.0/lib/one_gadget/fetchers/amd64.rb:21:in `candidates'
    from /var/lib/gems/2.3.0/gems/one_gadget-1.6.0/lib/one_gadget/fetchers/base.rb:19:in `find'
    from /var/lib/gems/2.3.0/gems/one_gadget-1.6.0/lib/one_gadget/fetcher.rb:32:in `from_file'
    from /var/lib/gems/2.3.0/gems/one_gadget-1.6.0/lib/one_gadget.rb:35:in `gadgets'
    from /var/lib/gems/2.3.0/gems/one_gadget-1.6.0/bin/one_gadget:67:in `<top (required)>'
    from /usr/local/bin/one_gadget:23:in `load'
    from /usr/local/bin/one_gadget:23:in `<main>'
```

any suggestions?

**Comment by david942j** [comment]
I haven't check the file yet, but the error looks like the input file is not a valid libc.so.6 since one_gadget can't find the string `/bin/sh` in it

**Comment by expend20** [comment]
oh, sorry, my bad

**Comment by KevOrr** [comment]
Maybe a better error message then? `jmp_case_candidates` should make sure that `str_offset('/bin/sh')` returned an int, and if it didn't (e.g. it return `nil`), then it should fail with a descriptive error message.

**Comment by david942j** [comment]
@KevOrr sound great
